

bootstrap.adb: 
	gnatbind -Lmidiplayerlib -o bootstrap.adb lib/midiplayerlib.ali -I../Ada-Midi/lib/ -I../Ada-Midi-Player/obj  -I../Ada-Synthetizer/lib/  -I../Ada-Synthetizer/drivers/alsa-binding/obj -I../Ada-Synthetizer-Bank/obj



