name = "adasynthetizer"
description = "Ada Synthetizer Suite"
version = "0.25"

licenses = "Apache-2.0"
authors = ["Patrice Freydiere"]
maintainers = ["Patrice Freydiere <frett27@gmail.com>"]
maintainers-logins = ["frett27"]

project-files = [
"Ada-Synthetizer/synthetizer.gpr",
"Ada-Midi-Player/adamidiplayer.gpr",
"Ada-Midi/adamidi.gpr"
]

[[actions.'case(os)'.linux]]
type="pre-build"
command = ["make"]



#[[external]]
#kind = "system"
#[external.origin."case(distribution)"]
#"debian|ubuntu" = ["libasound-dev"]
#
