#include <stdio.h>
#include <alsa/asoundlib.h>

int main() {
   printf ("package Sound.Constants is\n");
   printf ("   Playback_Stream   : constant := %u;\n", (unsigned int)SND_PCM_STREAM_PLAYBACK);
   printf ("   Capture_Stream    : constant := %u;\n", (unsigned int)SND_PCM_STREAM_CAPTURE);
   printf ("\n");
   printf ("   State_Open         : constant := %u;\n", (unsigned int)SND_PCM_STATE_OPEN);
   printf ("   State_Setup        : constant := %u;\n", (unsigned int)SND_PCM_STATE_SETUP);
   printf ("   State_Prepared     : constant := %u;\n", (unsigned int)SND_PCM_STATE_PREPARED);
   printf ("   State_Running      : constant := %u;\n", (unsigned int)SND_PCM_STATE_RUNNING);
   printf ("   State_XRun         : constant := %u;\n", (unsigned int)SND_PCM_STATE_XRUN);
   printf ("   State_Draining     : constant := %u;\n", (unsigned int)SND_PCM_STATE_DRAINING);
   printf ("   State_Paused       : constant := %u;\n", (unsigned int)SND_PCM_STATE_PAUSED);
   printf ("   State_Suspended    : constant := %u;\n", (unsigned int)SND_PCM_STATE_SUSPENDED);
   printf ("   State_Disconnected : constant := %u;\n", (unsigned int)SND_PCM_STATE_DISCONNECTED);
   printf ("\n");
   printf ("   Sound_Stream_Non_Blocking : constant := %u;\n", (unsigned int)SND_PCM_NONBLOCK);
   printf ("   Sound_Stream_Asynchronous : constant := %u;\n", (unsigned int)SND_PCM_ASYNC);
   printf ("\n");
   printf ("   Format_Unknown                       : constant := %d;\n", (int)SND_PCM_FORMAT_UNKNOWN);
   printf ("   Format_Signed_8_Bit                  : constant := %d;\n", (int)SND_PCM_FORMAT_S8);
   printf ("   Format_Unsigned_8_Bit                : constant := %d;\n", (int)SND_PCM_FORMAT_U8);
   printf ("   Format_Signed_16_Bit_Little_Endian   : constant := %d;\n", (int)SND_PCM_FORMAT_S16_LE);
   printf ("   Format_Signed_16_Bit_Big_Endian      : constant := %d;\n", (int)SND_PCM_FORMAT_S16_BE);
   printf ("   Format_Unsigned_16_Bit_Little_Endian : constant := %d;\n", (int)SND_PCM_FORMAT_U16_LE);
   printf ("   Format_Unsigned_16_Bit_Big_Endian    : constant := %d;\n", (int)SND_PCM_FORMAT_U16_BE);
   printf ("   Format_Signed_24_Bit_Little_Endian   : constant := %d;\n", (int)SND_PCM_FORMAT_S24_LE);
   printf ("   Format_Signed_24_Bit_Big_Endian      : constant := %d;\n", (int)SND_PCM_FORMAT_S24_BE);
   printf ("   Format_Unsigned_24_Bit_Little_Endian : constant := %d;\n", (int)SND_PCM_FORMAT_U24_LE);
   printf ("   Format_Unsigned_24_Bit_Big_Endian    : constant := %d;\n", (int)SND_PCM_FORMAT_U24_BE);
   printf ("   Format_Signed_32_Bit_Little_Endian   : constant := %d;\n", (int)SND_PCM_FORMAT_S32_LE);
   printf ("   Format_Signed_32_Bit_Big_Endian      : constant := %d;\n", (int)SND_PCM_FORMAT_S32_BE);
   printf ("   Format_Unsigned_32_Bit_Little_Endian : constant := %d;\n", (int)SND_PCM_FORMAT_U32_LE);
   printf ("   Format_Unsigned_32_Bit_Big_Endian    : constant := %d;\n", (int)SND_PCM_FORMAT_U32_BE);
   printf ("   Format_FLOAT_LE                      : constant := %d;\n", (int)SND_PCM_FORMAT_FLOAT_LE);
   printf ("   Format_FLOAT_BE                      : constant := %d;\n", (int)SND_PCM_FORMAT_FLOAT_BE);
   printf ("   Format_FLOAT64_LE                    : constant := %d;\n", (int)SND_PCM_FORMAT_FLOAT64_LE);
   printf ("   Format_FLOAT64_BE                    : constant := %d;\n", (int)SND_PCM_FORMAT_FLOAT64_BE);
   printf ("   Format_IEC958_SUBFRAME_LE            : constant := %d;\n", (int)SND_PCM_FORMAT_IEC958_SUBFRAME_LE);
   printf ("   Format_IEC958_SUBFRAME_BE            : constant := %d;\n", (int)SND_PCM_FORMAT_IEC958_SUBFRAME_BE);
   printf ("   Format_MU_LAW                        : constant := %d;\n", (int)SND_PCM_FORMAT_MU_LAW);
   printf ("   Format_A_LAW                         : constant := %d;\n", (int)SND_PCM_FORMAT_A_LAW);
   printf ("   Format_IMA_ADPCM                     : constant := %d;\n", (int)SND_PCM_FORMAT_IMA_ADPCM);
   printf ("   Format_MPEG                          : constant := %d;\n", (int)SND_PCM_FORMAT_MPEG);
   printf ("   Format_GSM                           : constant := %d;\n", (int)SND_PCM_FORMAT_GSM);
   printf ("   Format_SPECIAL                       : constant := %d;\n", (int)SND_PCM_FORMAT_SPECIAL);
   printf ("   Format_S24_3LE                       : constant := %d;\n", (int)SND_PCM_FORMAT_S24_3LE);
   printf ("   Format_S24_3BE                       : constant := %d;\n", (int)SND_PCM_FORMAT_S24_3BE);
   printf ("   Format_U24_3LE                       : constant := %d;\n", (int)SND_PCM_FORMAT_U24_3LE);
   printf ("   Format_U24_3BE                       : constant := %d;\n", (int)SND_PCM_FORMAT_U24_3BE);
   printf ("   Format_S20_3LE                       : constant := %d;\n", (int)SND_PCM_FORMAT_S20_3LE);
   printf ("   Format_S20_3BE                       : constant := %d;\n", (int)SND_PCM_FORMAT_S20_3BE);
   printf ("   Format_U20_3LE                       : constant := %d;\n", (int)SND_PCM_FORMAT_U20_3LE);
   printf ("   Format_U20_3BE                       : constant := %d;\n", (int)SND_PCM_FORMAT_U20_3BE);
   printf ("   Format_S18_3LE                       : constant := %d;\n", (int)SND_PCM_FORMAT_S18_3LE);
   printf ("   Format_S18_3BE                       : constant := %d;\n", (int)SND_PCM_FORMAT_S18_3BE);
   printf ("   Format_U18_3LE                       : constant := %d;\n", (int)SND_PCM_FORMAT_U18_3LE);
   printf ("   Format_U18_3BE                       : constant := %d;\n", (int)SND_PCM_FORMAT_U18_3BE);
   printf ("   Format_Last                          : constant := %d;\n", (int)SND_PCM_FORMAT_LAST);
   printf ("   Format_Signed_16_Bit                 : constant := %d;\n", (int)SND_PCM_FORMAT_S16);
   printf ("   Format_Unsigned_16_Bit               : constant := %d;\n", (int)SND_PCM_FORMAT_U16);
   printf ("\n");
   printf ("   Access_Memory_Mapped_Interleaved    : constant := %u;\n", (unsigned int)SND_PCM_ACCESS_MMAP_INTERLEAVED);
   printf ("   Access_Memory_Mapped_Noninterleaved : constant := %u;\n", (unsigned int)SND_PCM_ACCESS_MMAP_NONINTERLEAVED);
   printf ("   Access_Memory_Mapped_Complex        : constant := %u;\n", (unsigned int)SND_PCM_ACCESS_MMAP_COMPLEX);
   printf ("   Access_Read_Write_Interleaved       : constant := %u;\n", (unsigned int)SND_PCM_ACCESS_RW_INTERLEAVED);
   printf ("   Access_Read_Write_Noninterleaved    : constant := %u;\n", (unsigned int)SND_PCM_ACCESS_RW_NONINTERLEAVED);
   printf ("\n");
   printf ("   Error_Bad_File_Descriptor     : constant := %u;\n", (unsigned int)EBADFD);
   printf ("   Error_Pipe                    : constant := %u;\n", (unsigned int)EPIPE);
   printf ("   Error_Stream_Pipe             : constant := %u;\n", (unsigned int)ESTRPIPE);
   printf ("   Error_Interrupted_System_Call : constant := %u;\n", (unsigned int)EINTR);
   printf ("   Error_Again                   : constant := %u;\n", (unsigned int)EAGAIN);
   printf ("   Error_Unsupported_Feature     : constant := %u;\n", (unsigned int)ENOSYS);
   printf ("\n");
   printf ("   hw_params_Size : constant := %u;\n", (unsigned int)(8 * (snd_pcm_hw_params_sizeof())));
   printf ("end Sound.Constants;\n");
   return 0;
};
