PROJECT=ALSA_Binding

GENERATED_EXECUTABLES=bin/microphone_to_wav \
                      bin/record_stereo_wav \
                      bin/test_alsa_binding

GENERATED_SOURCES=src/sound-constants.ads \
                  src/alsa_binding.ads \
                  src/alsa_binding-mercurial.ads \

SCRIPTS=

TEST_OUTPUT=tests/results

